In [1]:
import pandas as pd
import numpy as np
import seaborn as sbn

In [2]:
df= pd.read_csv('emails.csv')

In [3]:
df

text  spam
0     Subject: naturally irresistible your corporate...     1
1     Subject: the stock trading gunslinger  fanny i...     1
2     Subject: unbelievable new homes made easy  im ...     1
3     Subject: 4 color printing special  request add...     1
4     Subject: do not have money , get software cds ...     1
...                                                 ...   ...
5723  Subject: re : research and development charges...     0
5724  Subject: re : receipts from visit  jim ,  than...     0
5725  Subject: re : enron case study update  wow ! a...     0
5726  Subject: re : interest  david ,  please , call...     0
5727  Subject: news : aurora 5 . 2 update  aurora ve...     0

[5728 rows x 2 columns]

In [4]:
df['spam'].value_counts()  #to see how many spam are there that is how many 0

0    4360
1    1368
Name: spam, dtype: int64

In [5]:
df.shape

(5728, 2)

In [6]:
df.drop_duplicates(inplace=True)

In [7]:
df

text  spam
0     Subject: naturally irresistible your corporate...     1
1     Subject: the stock trading gunslinger  fanny i...     1
2     Subject: unbelievable new homes made easy  im ...     1
3     Subject: 4 color printing special  request add...     1
4     Subject: do not have money , get software cds ...     1
...                                                 ...   ...
5723  Subject: re : research and development charges...     0
5724  Subject: re : receipts from visit  jim ,  than...     0
5725  Subject: re : enron case study update  wow ! a...     0
5726  Subject: re : interest  david ,  please , call...     0
5727  Subject: news : aurora 5 . 2 update  aurora ve...     0

[5695 rows x 2 columns]

In [8]:
df.isnull().sum()  #if there was null values we could have delete those rows without imbalancing the dataset #handling

text    0
spam    0
dtype: int64

In [9]:
df['spam'].value_counts()

0    4327
1    1368
Name: spam, dtype: int64

In [10]:
x= df.text.values

In [11]:
y= df.spam.values

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
xtrain,xtest,ytrain,ytest= train_test_split(x,y,test_size=.20)

# Data preprocessing

In [14]:
from sklearn.feature_extraction.text import CountVectorizer

In [15]:
cv= CountVectorizer()

In [16]:
x_train = cv.fit_transform(xtrain)

In [17]:
x_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

# ML algorithm

In [18]:
from sklearn.naive_bayes import MultinomialNB

In [19]:
model= MultinomialNB()
model.fit(x_train,ytrain)

MultinomialNB()

In [20]:
model.fit(x_train,ytrain)

MultinomialNB()

In [21]:
x_test=cv.transform(xtest)

In [22]:
x_test.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [24]:
model.score(x_test,ytest)

0.9929762949956101

In [28]:
emails=['Hey i am looking for machine learning tutorial','hey you win an iphon x giveaway for free please do the survey']

In [29]:
cv_email=cv.transform(emails)

In [30]:
model.predict(cv_email)

array([0, 1], dtype=int64)

# performance

In [31]:
pred= model.predict(x_test)

In [32]:
pred

array([1, 0, 1, ..., 0, 0, 0], dtype=int64)

In [33]:
from sklearn.metrics import accuracy_score

In [35]:
accuracy_score(ytest,pred)

0.9929762949956101

# confusion matrix

In [37]:
from sklearn.metrics import confusion_matrix

In [38]:
confusion_matrix(ytest,pred)

array([[858,   2],
       [  6, 273]], dtype=int64)

# classification report

In [39]:
from sklearn.metrics import classification_report

In [40]:
classification_report(ytest,pred)

'              precision    recall  f1-score   support\n\n           0       0.99      1.00      1.00       860\n           1       0.99      0.98      0.99       279\n\n    accuracy                           0.99      1139\n   macro avg       0.99      0.99      0.99      1139\nweighted avg       0.99      0.99      0.99      1139\n'

In [41]:
print(classification_report(ytest,pred))

              precision    recall  f1-score   support

           0       0.99      1.00      1.00       860
           1       0.99      0.98      0.99       279

    accuracy                           0.99      1139
   macro avg       0.99      0.99      0.99      1139
weighted avg       0.99      0.99      0.99      1139

